USE diary;
INSERT INTO `user` (`login`,`password`) VALUES ("test","geheim");
INSERT INTO `user` (`login`,`password`) VALUES ("erwin","geheim");
INSERT INTO `user` (`login`,`password`) VALUES ("johann.farm","geheim");
INSERT INTO `user` (`login`,`password`) VALUES ("karin","geheim");
INSERT INTO `user` (`login`,`password`) VALUES ("another.user","geheim");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Liebes Tagebuch, ich bin frisch verliebt! Letztens habe ich sie am FKF gesehen und es hat gefunkt.",3,"2014-01-17 09:41:31");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Liebes Tagebuch, heute habe ich sie in der Campina gesehen. Ich habe mich aber nicht getraut, sie anzusprechen. :(",3,"2014-01-20 22:27:20");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Liebes Tagebuch, ich kann nicht schlafen weil ich so arg verliebt bin.",3,"2014-01-21 04:30:56");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Liebes Tagebuch, ich bin komplett lieb!",1,"2014-01-09 09:57:55");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Liebes Tagebuch, ich habe endlich zu Gott gefunden!",2,"2014-10-17 16:07:05");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Liebes Tagebuch, eigentlich sollte ich lernen, aber ich muss die ganze Zeit an sie denken.",3,"2014-01-21 19:29:50");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Liebes Tagebuch, ich bin so verzweifelt. Sie hat mich heute gar nicht angesehen. :(",3,"2014-01-22 10:32:33");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Liebes Tagebuch, das hier ist streng geheim.",4,"2014-01-11 22:04:25");
INSERT INTO `entry` (`text`,`user_id`,`date`) VALUES ("Ein weiterer geheimer Eintrag.",4,"2014-01-18 05:45:10");